### ISSUE TITLE
Great work! Just reporting some issues IMHO!

### ISSUE THREAD

**Issue by emg110** [dragmz/vscode-teal#1]
The warning on "Unconditional branch just before the target label" does not suit TEAL above version 5 I guess , full directional routing on branch and label callings is available since then, so I propose to classify the errors and warnings on code based on the configured version of TEAL as well! All IMHO!  it's great!

**Comment by dragmz** [comment]
First, thanks A LOT for taking your time reviewing this. Means a lot to me.

The warning means there are no ops between the `b` and the target label, e.g.:
```teal
b test <- Unconditional branch just before the target label
// just a test
test:
```

Do you mean there are any use cases where this `b test` isn't just a redundant call?

**Comment by emg110** [comment]
Yes many scenarios include that but with many ref calls across the code above for example for having 2 branch one for error and one for log and return approved that way there will be many refs above those two branches that using calls to them

**Comment by dragmz** [comment]
Still seems like some interference to me. Would you mind checking your other extensions contributing to the "teal" language in:
`VS Code -> Extensions -> [Extension] -> Feature Contributions -> Languages (where ID is 'teal')`?

**Comment by dragmz** [comment]
I need some more help understanding this. Would you be able to show me an example of where this `b` is needed but still gets reported by the extension?

**Comment by emg110** [comment]
I just mentioned them in details above in my comment:
- A general error branch used by many blocks above but the code is at the end of TEAL doc
- A General log&return branch , again, used by many blocks above but the code is at the end of TEAL doc.
- ...

**Comment by dragmz** [comment]
I still see no point in having an unconditional branch call if there are no ops between the `b` and the target label and this is the case when the warning is issued. Do you have any valid TEAL example for this?

**Comment by emg110** [comment]
This is the exact example of my use case :
```
txn amount
int 1
>
bnz b_finale
callsub sub_check_something
b b_finale
b_finale:
```

**Comment by dragmz** [comment]
Why do you need this extra `b b_finale`

```
callsub sub_check_something
>>> b b_finale <<<
b_finale:
```
and not just
```
callsub sub_check_something
b_finale:
```
?

As far as I can see it gets reported due to a valid reason, which is redundancy because the execution will fall through the `b_finale:` after returning from the `callsub sub_check_something` anyway.

**Comment by emg110** [comment]
If I omit the b_finale branch and just put the code there , then how can I jump to that code and avoid duplicate coding when bnz b_finale (with last stack value === 1)?

**Comment by dragmz** [comment]
```
txn amount
int 1
>
bnz b_finale
callsub sub_check_something
b_finale:
```

I think this will do. It's about removing the `b` call, not the `b_finale` label.

**Comment by emg110** [comment]
What about after callsub? I need it to continue to b_finale to get finale!!!???

**Comment by emg110** [comment]
I suggested two new opcodes "callsubz" and "callsubnz" to JJ a while back on Discord, and following that up in there, which IMHO is the exact solution to this scenario! The names are self-explanatory

**Comment by dragmz** [comment]
> What about after callsub? I need it to continue to b_finale to get finale!!!???

Are you suggesting the execution won't continue into the `b_finale:` after `retsub` in the `sub_check_something` if the `b b_finale` call is removed?

**Comment by emg110** [comment]
I do not think that b_finale content would be executed without being called by b! Correct me if I'm wrong please!

**Comment by dragmz** [comment]
According to the docs, `callsub` will save the next instruction (which is the end of the program in this case) on the call stack before branching to `sub_check_something` (https://github.com/algorand/go-algorand/blob/master/data/transactions/logic/TEAL_opcodes.md#callsub-target) and then `retsub` will pop that instruction from the call stack and branch to it (https://github.com/algorand/go-algorand/blob/master/data/transactions/logic/TEAL_opcodes.md#retsub) so it looks all good to me, making the `b b_finale` redundant.

**Comment by dragmz** [comment]
Closing as not an issue. The examples provided here document a valid linter warning, where `b` call is just before its target label.

**Comment by emg110** [comment]
You were completely right! I am conducting some more tests and will put them here (contract Ids ) just as a reference. Thanks
